### ISSUE TITLE
TypeError in Python 3

### ISSUE THREAD

**Issue by arusahni** [mkwiatkowski/pinocchio#27]
Hi,

When attempting to get test timings, via `nosetests --with-stopwatch dir/`, my tests run and then I get the following traceback:

```
.............................................................................................
----------------------------------------------------------------------
Ran 93 tests in 1.866s

OK
Traceback (most recent call last):
  File "/Users/aru/.virtualenvs/<snip>/bin/nosetests", line 11, in <module>
    sys.exit(run_exit())
  File "/Users/aru/.virtualenvs/<snip>/lib/python3.4/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/unittest/main.py", line 93, in __init__
    self.runTests()
  File "/Users/aru/.virtualenvs/<snip>/lib/python3.4/site-packages/nose/core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "/Users/aru/.virtualenvs/<snip>/lib/python3.4/site-packages/nose/core.py", line 68, in run
    self.config.plugins.finalize(result)
  File "/Users/aru/.virtualenvs/<snip>/lib/python3.4/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/Users/aru/.virtualenvs/<snip>/lib/python3.4/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/Users/aru/.virtualenvs/<snip>/lib/python3.4/site-packages/pinocchio/stopwatch.py", line 94, in finalize
    dump(self.times, fp)
TypeError: must be str, not bytes
```

Subsequent runs fail to execute the tests altogether, and present a different error:

```
Traceback (most recent call last):
  File "/Users/aru/.virtualenvs/<snip>/bin/nosetests", line 11, in <module>
    sys.exit(run_exit())
  File "/Users/aru/.virtualenvs/<snip>/lib/python3.4/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/unittest/main.py", line 92, in __init__
    self.parseArgs(argv)
  File "/Users/aru/.virtualenvs/<snip>/lib/python3.4/site-packages/nose/core.py", line 145, in parseArgs
    self.config.configure(argv, doc=self.usage())
  File "/Users/aru/.virtualenvs/<snip>/lib/python3.4/site-packages/nose/config.py", line 347, in configure
    self.plugins.begin()
  File "/Users/aru/.virtualenvs/<snip>/lib/python3.4/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/Users/aru/.virtualenvs/<snip>/lib/python3.4/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/Users/aru/.virtualenvs/<snip>/lib/python3.4/site-packages/pinocchio/stopwatch.py", line 68, in begin
    self.times = load(open(self.stopwatch_file))
TypeError: 'str' does not support the buffer interface
```

Removing the `.nose-stopwatch-times` file allows me to run my tests, but still exits with the same error.  I'm using Python 3.4 on OS X w/ nose 1.3.7 and Pinocchio 0.4.2.

Thanks!

**Comment by mkwiatkowski** [comment]
Thank you for the report!

Version on PyPI hasn't been updated in a while (sorry!), could you retest using a version from github?

**Comment by arusahni** [comment]
I'm able to replicate this behavior using the version on `master`.

**Comment by mkwiatkowski** [comment]
OK, thank you, I will look into it.

**Comment by mkwiatkowski** [comment]
@arusahni Fixed in master.

**Comment by arusahni** [comment]
Awesome. Thank you! :100:
